# Generated by Django 4.2.7 on 2023-12-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transactions_is_bankrupt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='is_bankrupt',
        ),
    ]
